services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: campingCars
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - mysql-data:/var/lib/mysql

  mysql-microservice:
    image: mysql:8
    container_name: mysql-microservice
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: new_brands
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
    ports:
      - "3307:3306"   # Different port (3307) for Microservice DB
    networks:
      - my_network
    volumes:
      - mysql-microservice-data:/var/lib/mysql
      - C:\Users\vikto\Desktop\Java Web\Spring Advanced\src code\Camping_Cars_new_brand_rest\new_brand_rest_app/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql

  camping-cars:
    build: .
    container_name: camping-cars
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/campingCars?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      MICROSERVICE_URL: http://brands-microservice:8081
      OPENEXCHANGERATES_APP_ID: ${APP_ID}
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - my_network

  brands-microservice:
    build: C:\Users\vikto\Desktop\Java Web\Spring Advanced\src code\Camping_Cars_new_brand_rest\new_brand_rest_app
    container_name: brands-microservice
    depends_on:
      mysql-microservice:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-microservice:3306/new_brands?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8081:8081"
    networks:
      - my_network

networks:
  my_network:

volumes:
  mysql-data:
  mysql-microservice-data:
