spring:
    profiles:
        active: default
    application:
        name: campingCars
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/campingCars?createDatabaseIfNotExist=true
        username: ${MYSQL_USER:}
        password: ${MYSQL_PASS:}
    sql:
        init:
            mode: never
    mvc:
        hiddenmethod:
            filter:
                enabled: true

    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true

    thymeleaf: # Thymeleaf
        cache: false
        mode: HTML
        encoding: UTF-8
        prefix: file:src/main/resources/templates/
    web:
        resources:
            static-locations: file:src/main/resources/static/
            cache:
                period: 0

logging:
    level:
        org.hibernate.SQL: DEBUG
        org.hibernate.orm.jdbc.bind: TRACE

open.exchange.rates:
    schema: https
    host: openexchangerates.org
    path: /api/latest.json
    app_id: ${APP_ID:}
    symbols: BGN
    enabled: false

brand:
    api:
        baseUrl: "${BRAND_BASE_URL:http://localhost:8081}"

jwt:
    secret: ${JWT_KEY:WSdv1kEE1tCT1a8ihRSqfwMNzlPBq8IWSdv1kEE1tCT1a8ihRSqfwMNzlPBq8IWSdv1kEE1tCT1a8ihRSqfwMNzlPBq8I}
    expiration: ${JWT_EXPIRATION:60000}

#mail:
#    mobilele: mobilele@example.com
#    host: localhost
#    port: 1025
#    username: ${MAIL_USER:softuni}
#    password: ${MAIL_PASSWORD:softuni}