spring:
    profiles:
        active: default
    application:
        name: campingCars
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql-db:3306/campingCars?createDatabaseIfNotExist=true
        username: ${MYSQL_USER:}
        password: ${MYSQL_PASS:}
    sql:
        init:
            mode: always
    mvc:
        hiddenmethod:
            filter:
                enabled: true

    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true

    thymeleaf: # Thymeleaf
        cache: false
        mode: HTML
        encoding: UTF-8
        prefix: classpath:/templates/
        suffix: .html
        check-template-location: true
        enabled: true
    web:
        resources:
            static-locations: classpath:/static/
            cache:
                period: 0

logging:
    level:
        org.hibernate.SQL: DEBUG
        org.hibernate.orm.jdbc.bind: TRACE

open.exchange.rates:
    schema: https
    host: openexchangerates.org
    path: /api/latest.json
    app_id: ${APP_ID}
    symbols: BGN
    enabled: false

brand:
    api:
        baseUrl: ${BRAND_BASE_URL:}

jwt:
    secret: ${JWT_KEY:}


management:
    server:
        port: 9090
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: "*"

#mail:
#    mobilele: mobilele@example.com
#    host: localhost
#    port: 1025
#    username: ${MAIL_USER:softuni}
#    password: ${MAIL_PASSWORD:softuni}